import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SavedListingsProvider } from "@/components/context/SavedListingsContext";
import { CompareListingsProvider } from "@/components/context/CompareListingsContext";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/components/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
  <AuthProvider>
    <SavedListingsProvider>
      <CompareListingsProvider>
        <Navbar />
        {children}
        <Toaster
  position="top-right"
  toastOptions={{
    success: {
      duration: 1000,
    },
    error: {
      duration: 3500,
    },
  }}
/>
      </CompareListingsProvider>
    </SavedListingsProvider>
  </AuthProvider>
</body>
    </html>
  );
}
